package com.gida.models.enums;

public enum PositionType {
    DIRECTOR,
    FINANCE_DIRECTOR,
    CHIEF_ACCOUNTANT,
    HEAD_OF_THE_HOUSEHOLD,
    DEPUTY_DIRECTOR_FOR_COMMERCIAL_AFFAIRS,
    DEPUTY_DIRECTOR_FOR_HUMAN_RESOURCES_MANAGMENT,
    MANAGER,
    HUMAN_RESOURCES_MANAGER,
    HEAD_OF_HUMAN_RESOURCES_DEPARTMENT,
    MANAGER_OF_THE_DEPARTMENT,
    ACCOUNTER

}
